// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function run(options) {
  console.log(options);
}

console.log({
      path: "test"
    });

exports.run = run;
/*  Not a pure module */
