// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ava = require("@dzakh/rescript-ava/src/Ava.bs.js");
var Ava$1 = require("ava").default;

Ava.test(Ava$1, "Test", (function (t) {
        t.pass(undefined);
      }));

/*  Not a pure module */
